#!/bin/bash

echo "=== Checking Server Status ==="
echo ""
echo "Run these commands on your server:"
echo ""
echo "1. Check if Godot server is running:"
echo "   ps aux | grep godot"
echo ""
echo "2. If not running, check the screen session:"
echo "   screen -list"
echo ""
echo "3. To reattach to screen session:"
echo "   screen -r godot_server"
echo ""
echo "4. If no screen session, start the server:"
echo "   cd ~/spaceloop"
echo "   screen -dmS godot_server ./run_server.sh"
echo ""
echo "5. Check nginx error logs:"
echo "   sudo tail -f /var/log/nginx/error.log"
echo ""
echo "6. Test local connection to game server:"
echo "   curl http://localhost:8910"
echo ""
echo "7. Check if server is listening on port 8910:"
echo "   sudo netstat -tlnp | grep 8910"