#!/bin/bash

echo "=== Nginx SSL Setup for Spaceloop ==="
echo ""
echo "This script will help you set up nginx reverse proxy for SSL/WebSocket support."
echo ""
echo "Prerequisites:"
echo "1. You must have already obtained SSL certificates using certbot"
echo "2. You must be able to SSH into your server"
echo ""
echo "Steps to complete on your GCP server:"
echo ""
echo "1. SSH into your server:"
echo "   gcloud compute ssh spaceloop-server --zone=us-central1-a"
echo ""
echo "2. Install nginx if not already installed:"
echo "   sudo apt update"
echo "   sudo apt install -y nginx"
echo ""
echo "3. Create the nginx configuration:"
echo "   sudo nano /etc/nginx/sites-available/spaceloop"
echo ""
echo "4. Copy the contents from nginx-spaceloop.conf into the file"
echo ""
echo "5. Enable the site:"
echo "   sudo ln -s /etc/nginx/sites-available/spaceloop /etc/nginx/sites-enabled/"
echo "   sudo rm /etc/nginx/sites-enabled/default"
echo ""
echo "6. Test nginx configuration:"
echo "   sudo nginx -t"
echo ""
echo "7. Restart nginx:"
echo "   sudo systemctl restart nginx"
echo ""
echo "8. Open port 443 in GCP firewall:"
echo "   exit  # Exit from SSH first"
echo "   gcloud compute firewall-rules update spaceloop-game \\"
echo "     --allow udp:8910,tcp:8911,tcp:443,tcp:80"
echo ""
echo "9. Test the connection:"
echo "   - Open your HTML5 game on itch.io or another HTTPS site"
echo "   - It should now connect using wss://mattsdevlog.com"
echo ""
echo "The nginx configuration file is available at: nginx-spaceloop.conf"